# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\MainControl_QA\TestDevelopment\O2T\O2T.ui'
#
# Created: Tue Aug 11 12:47:01 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import *
from PyQt4.QtGui import   * #QDialog, QApplication, QMainWindow, 
from PyQt4.QtCore import *  #pyqtSignature

try:
    _fromUtf8 = QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig)
    
class mycombobox(QComboBox,QLineEdit):
    def __init__(self,parent=None): 
        super(mycombobox,self).__init__(parent)   
        
    def keyPressEvent(self,event):
        QComboBox.keyPressEvent(self,event)
        keyEvent = QKeyEvent(event) 
        if keyEvent.key() == 16777220: 
            self.emit(SIGNAL('returnPressed'))


class Ui_O2Tool(object):
    def setupUi(self, O2Tool):
        O2Tool.setObjectName(_fromUtf8("O2Tool"))
        O2Tool.resize(636, 500)
        O2Tool.setToolButtonStyle(Qt.ToolButtonTextBesideIcon)
        O2Tool.setWindowFlags(Qt.WindowMinimizeButtonHint) 
        icon = QIcon()
        try:
            icon.addPixmap(QPixmap(_fromUtf8("./O2tool.ico")), QIcon.Normal, QIcon.Off)
            icon.addPixmap(QPixmap(_fromUtf8("./O2tool.ico")), QIcon.Normal, QIcon.On)
            O2Tool.setWindowIcon(icon)
            print " get the ico"
        except Exception, e:
            print e
        self.centralwidget = QWidget(O2Tool)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QRect(10, 10, 611, 421))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet(_fromUtf8(""))
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_ADS = QWidget()
        self.tab_ADS.setObjectName(_fromUtf8("tab_ADS"))
        self.groupBox_2 = QGroupBox(self.tab_ADS)
        self.groupBox_2.setGeometry(QRect(10, 220, 561, 161))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.layoutWidget = QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QRect(10, 20, 521, 131))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_limit = QGridLayout(self.layoutWidget)
        self.gridLayout_limit.setMargin(0)
        self.gridLayout_limit.setObjectName(_fromUtf8("gridLayout_limit"))
        self.pushButton_loadRadius = QPushButton(self.layoutWidget)
        self.pushButton_loadRadius.setEnabled(False)
        self.pushButton_loadRadius.setObjectName(_fromUtf8("pushButton_loadRadius"))
        self.gridLayout_limit.addWidget(self.pushButton_loadRadius, 2, 2, 1, 1)
        self.label_10 = QLabel(self.layoutWidget)
        self.label_10.setLayoutDirection(Qt.LeftToRight)
        self.label_10.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_limit.addWidget(self.label_10, 3, 0, 1, 1)
        self.pushButton_loadgearbox = QPushButton(self.layoutWidget)
        self.pushButton_loadgearbox.setEnabled(False)
        self.pushButton_loadgearbox.setObjectName(_fromUtf8("pushButton_loadgearbox"))
        self.gridLayout_limit.addWidget(self.pushButton_loadgearbox, 3, 2, 1, 1)
        self.pushButton_setRadius = QPushButton(self.layoutWidget)
        self.pushButton_setRadius.setEnabled(False)
        self.pushButton_setRadius.setObjectName(_fromUtf8("pushButton_setRadius"))
        self.gridLayout_limit.addWidget(self.pushButton_setRadius, 2, 3, 1, 1)
        self.label_9 = QLabel(self.layoutWidget)
        self.label_9.setLayoutDirection(Qt.LeftToRight)
        self.label_9.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_limit.addWidget(self.label_9, 2, 0, 1, 1)
        self.lineEdit_Gearbox = QLineEdit(self.layoutWidget)
        self.lineEdit_Gearbox.setText(_fromUtf8(""))
        self.lineEdit_Gearbox.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.lineEdit_Gearbox.setObjectName(_fromUtf8("lineEdit_Gearbox"))
        self.gridLayout_limit.addWidget(self.lineEdit_Gearbox, 3, 1, 1, 1)
        self.lineEdit_Radius = QLineEdit(self.layoutWidget)
        self.lineEdit_Radius.setText(_fromUtf8(""))
        self.lineEdit_Radius.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.lineEdit_Radius.setObjectName(_fromUtf8("lineEdit_Radius"))
        self.gridLayout_limit.addWidget(self.lineEdit_Radius, 2, 1, 1, 1)
        self.pushButton_enableGearbox = QPushButton(self.layoutWidget)
        self.pushButton_enableGearbox.setEnabled(False)
        self.pushButton_enableGearbox.setObjectName(_fromUtf8("pushButton_enableGearbox"))
        self.gridLayout_limit.addWidget(self.pushButton_enableGearbox, 3, 3, 1, 1)
        self.pushButton_disableGearbox = QPushButton(self.layoutWidget)
        self.pushButton_disableGearbox.setEnabled(False)
        self.pushButton_disableGearbox.setObjectName(_fromUtf8("pushButton_disableGearbox"))
        self.gridLayout_limit.addWidget(self.pushButton_disableGearbox, 3, 4, 1, 1)
        self.pushButton_loadWindspeed = QPushButton(self.layoutWidget)
        self.pushButton_loadWindspeed.setEnabled(False)
        self.pushButton_loadWindspeed.setObjectName(_fromUtf8("pushButton_loadWindspeed"))
        self.gridLayout_limit.addWidget(self.pushButton_loadWindspeed, 0, 2, 1, 1)
        self.pushButton_resetScada = QPushButton(self.layoutWidget)
        self.pushButton_resetScada.setEnabled(False)
        self.pushButton_resetScada.setObjectName(_fromUtf8("pushButton_resetScada"))
        self.gridLayout_limit.addWidget(self.pushButton_resetScada, 1, 4, 1, 1)
        self.lineEdit_windspeed = QLineEdit(self.layoutWidget)
        self.lineEdit_windspeed.setText(_fromUtf8(""))
        self.lineEdit_windspeed.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.lineEdit_windspeed.setObjectName(_fromUtf8("lineEdit_windspeed"))
        self.gridLayout_limit.addWidget(self.lineEdit_windspeed, 0, 1, 1, 1)
        self.label_11 = QLabel(self.layoutWidget)
        self.label_11.setLayoutDirection(Qt.LeftToRight)
        self.label_11.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_limit.addWidget(self.label_11, 0, 0, 1, 1)
        self.pushButton_setWindspeed = QPushButton(self.layoutWidget)
        self.pushButton_setWindspeed.setEnabled(False)
        self.pushButton_setWindspeed.setObjectName(_fromUtf8("pushButton_setWindspeed"))
        self.gridLayout_limit.addWidget(self.pushButton_setWindspeed, 0, 3, 1, 1)
        self.pushButton_loadScada = QPushButton(self.layoutWidget)
        self.pushButton_loadScada.setEnabled(False)
        self.pushButton_loadScada.setObjectName(_fromUtf8("pushButton_loadScada"))
        self.gridLayout_limit.addWidget(self.pushButton_loadScada, 1, 2, 1, 1)
        self.label_8 = QLabel(self.layoutWidget)
        self.label_8.setLayoutDirection(Qt.LeftToRight)
        self.label_8.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_limit.addWidget(self.label_8, 1, 0, 1, 1)
        self.lineEdit_Scada = QLineEdit(self.layoutWidget)
        self.lineEdit_Scada.setText(_fromUtf8(""))
        self.lineEdit_Scada.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.lineEdit_Scada.setObjectName(_fromUtf8("lineEdit_Scada"))
        self.gridLayout_limit.addWidget(self.lineEdit_Scada, 1, 1, 1, 1)
        self.pushButton_setScada = QPushButton(self.layoutWidget)
        self.pushButton_setScada.setEnabled(False)
        self.pushButton_setScada.setObjectName(_fromUtf8("pushButton_setScada"))
        self.gridLayout_limit.addWidget(self.pushButton_setScada, 1, 3, 1, 1)
        self.groupBox_3 = QGroupBox(self.tab_ADS)
        self.groupBox_3.setGeometry(QRect(10, 0, 561, 211))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.layoutWidget1 = QWidget(self.groupBox_3)
        self.layoutWidget1.setGeometry(QRect(10, 20, 521, 166))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout = QGridLayout(self.layoutWidget1)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))

        
        self.label_42 = QLabel(self.layoutWidget1)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_42.sizePolicy().hasHeightForWidth())
        self.label_42.setSizePolicy(sizePolicy)
        self.label_42.setLayoutDirection(Qt.LeftToRight)
        self.label_42.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout.addWidget(self.label_42, 0, 0, 1, 1)
        self.comboBox_version = QComboBox(self.layoutWidget1)
        self.comboBox_version.setMaximumSize(QSize(151, 20))
        self.comboBox_version.setObjectName(_fromUtf8("comboBox_version"))
        self.gridLayout.addWidget(self.comboBox_version, 0, 1, 1, 1)                
        
        self.label = QLabel(self.layoutWidget1)
        self.label.setSizePolicy(sizePolicy)
        self.label.setLayoutDirection(Qt.LeftToRight)
        self.label.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)        
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.comboBox_ip = mycombobox(self.layoutWidget1)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_ip.sizePolicy().hasHeightForWidth())
        self.comboBox_ip.setSizePolicy(sizePolicy)
        self.comboBox_ip.setMinimumSize(QSize(180, 0))
        self.comboBox_ip.setMaximumSize(QSize(99, 16777215))
        self.comboBox_ip.setEditable(True)
        self.comboBox_ip.setInsertPolicy(QComboBox.NoInsert)
        self.comboBox_ip.setObjectName(_fromUtf8("comboBox_ip"))
        self.horizontalLayout_2.addWidget(self.comboBox_ip)
        self.lineEdit_port = QLineEdit(self.layoutWidget1)
        self.lineEdit_port.setMinimumSize(QSize(20, 0))
        self.lineEdit_port.setMaximumSize(QSize(35, 16777215))
        self.lineEdit_port.setObjectName(_fromUtf8("lineEdit_port"))
        self.horizontalLayout_2.addWidget(self.lineEdit_port)
        self.label_version = QLabel(self.layoutWidget1)
        self.label_version.setText(_fromUtf8(""))
        self.label_version.setObjectName(_fromUtf8("label_version"))
        self.horizontalLayout_2.addWidget(self.label_version)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)  
        self.pushButton_adsConnect = QPushButton(self.layoutWidget1)
        self.pushButton_adsConnect.setObjectName(_fromUtf8("pushButton_adsConnect"))
        self.gridLayout.addWidget(self.pushButton_adsConnect, 1, 2, 1, 1)
        
        self.label_4 = QLabel(self.layoutWidget1)
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setLayoutDirection(Qt.LeftToRight)
        self.label_4.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.comboBox_name = mycombobox(self.layoutWidget1)
        self.comboBox_name.setEditable(True)
        self.comboBox_name.setObjectName(_fromUtf8("comboBox_name"))
        self.gridLayout.addWidget(self.comboBox_name, 2, 1, 1, 1)
        self.pushButton_adsLoad = QPushButton(self.layoutWidget1)
        self.pushButton_adsLoad.setEnabled(False)
        self.pushButton_adsLoad.setObjectName(_fromUtf8("pushButton_adsLoad"))
        self.gridLayout.addWidget(self.pushButton_adsLoad, 2, 2, 1, 1)
        
        self.label_3 = QLabel(self.layoutWidget1)
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setLayoutDirection(Qt.LeftToRight)
        self.label_3.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.lineEdit_type = QLineEdit(self.layoutWidget1)
        self.lineEdit_type.setText(_fromUtf8(""))
        self.lineEdit_type.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.lineEdit_type.setObjectName(_fromUtf8("lineEdit_type"))
        self.gridLayout.addWidget(self.lineEdit_type, 3, 1, 1, 1)
        
        self.label_5 = QLabel(self.layoutWidget1)
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setLayoutDirection(Qt.LeftToRight)
        self.label_5.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.lineEdit_value = QLineEdit(self.layoutWidget1)
        self.lineEdit_value.setEnabled(True)
        self.lineEdit_value.setText(_fromUtf8(""))
        self.lineEdit_value.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.lineEdit_value.setReadOnly(True)
        self.lineEdit_value.setObjectName(_fromUtf8("lineEdit_value"))
        self.gridLayout.addWidget(self.lineEdit_value, 4, 1, 1, 1)
        self.pushButton_adsTrigger = QPushButton(self.layoutWidget1)
        self.pushButton_adsTrigger.setEnabled(False)
        self.pushButton_adsTrigger.setObjectName(_fromUtf8("pushButton_adsTrigger"))
        self.gridLayout.addWidget(self.pushButton_adsTrigger, 4, 2, 1, 1)
        
        self.label_6 = QLabel(self.layoutWidget1)
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setLayoutDirection(Qt.LeftToRight)
        self.label_6.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.lineEdit_set = QLineEdit(self.layoutWidget1)
        self.lineEdit_set.setText(_fromUtf8(""))
        self.lineEdit_set.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.lineEdit_set.setObjectName(_fromUtf8("lineEdit_set"))
        self.gridLayout.addWidget(self.lineEdit_set, 5, 1, 1, 1)
        self.pushButton_adsWrite = QPushButton(self.layoutWidget1)
        self.pushButton_adsWrite.setEnabled(False)
        self.pushButton_adsWrite.setObjectName(_fromUtf8("pushButton_adsWrite"))
        self.gridLayout.addWidget(self.pushButton_adsWrite, 5, 2, 1, 1)

        

        
        
        self.tabWidget.addTab(self.tab_ADS, _fromUtf8(""))
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox = QGroupBox(self.tab_2)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QRect(20, 190, 491, 201))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))

        self.layoutWidget2 = QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QRect(15, 30, 450, 151))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout_5 = QGridLayout(self.layoutWidget2)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.pushButton_setSCrepeat = QPushButton(self.layoutWidget2)
        self.pushButton_setSCrepeat.setEnabled(False)
        self.pushButton_setSCrepeat.setMaximumSize(QSize(55, 16777215))
        self.pushButton_setSCrepeat.setObjectName(_fromUtf8("pushButton_setSCrepeat"))
        self.gridLayout_5.addWidget(self.pushButton_setSCrepeat, 4, 2, 1, 1)
        self.label_19 = QLabel(self.layoutWidget2)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_5.addWidget(self.label_19, 0, 0, 1, 1)
        self.label_20 = QLabel(self.layoutWidget2)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_5.addWidget(self.label_20, 1, 0, 1, 1)
        self.pushButton_loadSC = QPushButton(self.layoutWidget2)
        self.pushButton_loadSC.setEnabled(False)
        self.pushButton_loadSC.setMaximumSize(QSize(55, 16777215))
        self.pushButton_loadSC.setObjectName(_fromUtf8("pushButton_loadSC"))
        self.gridLayout_5.addWidget(self.pushButton_loadSC, 0, 2, 1, 1)
        self.lineEdit_SCcode = QLineEdit(self.layoutWidget2)
        self.lineEdit_SCcode.setText(_fromUtf8(""))
        self.lineEdit_SCcode.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.lineEdit_SCcode.setObjectName(_fromUtf8("lineEdit_SCcode"))
        self.gridLayout_5.addWidget(self.lineEdit_SCcode, 0, 1, 1, 1)
        self.lineEdit_SCsetType = QLineEdit(self.layoutWidget2)
        self.lineEdit_SCsetType.setText(_fromUtf8(""))
        self.lineEdit_SCsetType.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.lineEdit_SCsetType.setObjectName(_fromUtf8("lineEdit_SCsetType"))
        self.gridLayout_5.addWidget(self.lineEdit_SCsetType, 1, 1, 1, 1)
        self.label_23 = QLabel(self.layoutWidget2)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_5.addWidget(self.label_23, 2, 0, 1, 1)
        self.lineEdit_SCresetDelay = QLineEdit(self.layoutWidget2)
        self.lineEdit_SCresetDelay.setText(_fromUtf8(""))
        self.lineEdit_SCresetDelay.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.lineEdit_SCresetDelay.setObjectName(_fromUtf8("lineEdit_SCresetDelay"))
        self.gridLayout_5.addWidget(self.lineEdit_SCresetDelay, 3, 1, 1, 1)
        self.pushButton_setSCmode = QPushButton(self.layoutWidget2)
        self.pushButton_setSCmode.setEnabled(False)
        self.pushButton_setSCmode.setMaximumSize(QSize(55, 16777215))
        self.pushButton_setSCmode.setObjectName(_fromUtf8("pushButton_setSCmode"))
        self.gridLayout_5.addWidget(self.pushButton_setSCmode, 1, 2, 1, 1)
        self.lineEdit_SCrepeatTimes = QLineEdit(self.layoutWidget2)
        self.lineEdit_SCrepeatTimes.setText(_fromUtf8(""))
        self.lineEdit_SCrepeatTimes.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.lineEdit_SCrepeatTimes.setObjectName(_fromUtf8("lineEdit_SCrepeatTimes"))
        self.gridLayout_5.addWidget(self.lineEdit_SCrepeatTimes, 4, 1, 1, 1)
        self.label_24 = QLabel(self.layoutWidget2)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_5.addWidget(self.label_24, 3, 0, 1, 1)
        self.label_26 = QLabel(self.layoutWidget2)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_5.addWidget(self.label_26, 4, 0, 1, 1)
        self.pushButton_setSCdelay = QPushButton(self.layoutWidget2)
        self.pushButton_setSCdelay.setEnabled(False)
        self.pushButton_setSCdelay.setMaximumSize(QSize(55, 16777215))
        self.pushButton_setSCdelay.setObjectName(_fromUtf8("pushButton_setSCdelay"))
        self.gridLayout_5.addWidget(self.pushButton_setSCdelay, 2, 2, 1, 1)
        self.lineEdit_SCsetdelay = QLineEdit(self.layoutWidget2)
        self.lineEdit_SCsetdelay.setText(_fromUtf8(""))
        self.lineEdit_SCsetdelay.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.lineEdit_SCsetdelay.setObjectName(_fromUtf8("lineEdit_SCsetdelay"))
        self.gridLayout_5.addWidget(self.lineEdit_SCsetdelay, 2, 1, 1, 1)
        self.pushButton_setSCredelay = QPushButton(self.layoutWidget2)
        self.pushButton_setSCredelay.setEnabled(False)
        self.pushButton_setSCredelay.setMaximumSize(QSize(55, 16777215))
        self.pushButton_setSCredelay.setObjectName(_fromUtf8("pushButton_setSCredelay"))
        self.gridLayout_5.addWidget(self.pushButton_setSCredelay, 3, 2, 1, 1)
        #sc id
        self.label_25 = QLabel(self.layoutWidget2)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_25.setAlignment(Qt.AlignCenter)
        self.gridLayout_5.addWidget(self.label_25, 0, 3, 1, 1)
        
        self.lineEdit_SCid = QLineEdit(self.layoutWidget2)
        self.lineEdit_SCid.setEnabled(False)
        self.lineEdit_SCid.setGeometry(QRect(400, 20, 51, 20))
        self.lineEdit_SCid.setText(_fromUtf8(""))
        self.lineEdit_SCid.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.lineEdit_SCid.setObjectName(_fromUtf8("lineEdit_SCid"))        
        self.gridLayout_5.addWidget(self.lineEdit_SCid, 0, 4, 1, 1)
        #bplevel
        self.label_27 = QLabel(self.layoutWidget2)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_5.addWidget(self.label_27, 1, 3, 1, 1)        
        self.lineEdit_SCbplevel = QLineEdit(self.layoutWidget2)
        self.lineEdit_SCbplevel.setText(_fromUtf8(""))
        self.lineEdit_SCbplevel.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.lineEdit_SCbplevel.setObjectName(_fromUtf8("lineEdit_SCbplevel"))
        self.gridLayout_5.addWidget(self.lineEdit_SCbplevel, 1, 4, 1, 1)
        
        self.pushButton_setSCbplevel = QPushButton(self.layoutWidget2)
        self.pushButton_setSCbplevel.setEnabled(False)
        self.pushButton_setSCbplevel.setMaximumSize(QSize(55, 16777215))
        self.pushButton_setSCbplevel.setObjectName(_fromUtf8("pushButton_setSCbplevel"))
        self.gridLayout_5.addWidget(self.pushButton_setSCbplevel, 1, 5, 1, 1)
        
        #yplevel
        self.label_yp = QLabel(self.layoutWidget2)
        self.label_yp.setObjectName(_fromUtf8("label_yp"))
        self.gridLayout_5.addWidget(self.label_yp, 2, 3, 1, 1)        
        self.lineEdit_SCyplevel = QLineEdit(self.layoutWidget2)
        self.lineEdit_SCyplevel.setText(_fromUtf8(""))
        self.lineEdit_SCyplevel.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.lineEdit_SCyplevel.setObjectName(_fromUtf8("lineEdit_SCyplevel"))
        self.gridLayout_5.addWidget(self.lineEdit_SCyplevel, 2, 4, 1, 1)
        
        self.pushButton_setSCyplevel = QPushButton(self.layoutWidget2)
        self.pushButton_setSCyplevel.setEnabled(False)
        self.pushButton_setSCyplevel.setMaximumSize(QSize(55, 16777215))
        self.pushButton_setSCyplevel.setObjectName(_fromUtf8("pushButton_setSCyplevel"))
        self.gridLayout_5.addWidget(self.pushButton_setSCyplevel, 2, 5, 1, 1)        
        
        #disable sc
        self.pushButton_disableSC = QPushButton(self.groupBox)
        self.pushButton_disableSC.setEnabled(False)
        self.pushButton_disableSC.setObjectName(_fromUtf8("pushButton_disableSC"))
        self.gridLayout_5.addWidget(self.pushButton_disableSC, 3, 4, 1, 1)
        
        self.pushButton_disableSClist = QPushButton(self.groupBox)
        self.pushButton_disableSClist.setEnabled(False)
        self.pushButton_disableSClist.setObjectName(_fromUtf8("pushButton_disableSClist"))
        self.gridLayout_5.addWidget(self.pushButton_disableSClist, 4, 4, 1, 1)        
        
        
        self.layoutWidget3 = QWidget(self.tab_2)
        self.layoutWidget3.setGeometry(QRect(20, 10, 491, 171))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.gridLayout_2 = QGridLayout(self.layoutWidget3)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        
        #simu
        self.label_simu = QLabel(self.layoutWidget3)
        self.label_simu.setObjectName(_fromUtf8("label_simu"))
        self.label_simu.setMaximumSize(QSize(55, 1000))
        self.gridLayout_2.addWidget(self.label_simu, 0, 0, 1, 1)        
        self.pushButton_enablesimu = QPushButton(self.layoutWidget3)
        self.pushButton_enablesimu.setEnabled(False)
        self.pushButton_enablesimu.setObjectName(_fromUtf8("pushButton_enablesimu"))
        self.gridLayout_2.addWidget(self.pushButton_enablesimu, 0, 1, 1, 1)        
        self.pushButton_ResetSaftyChain = QPushButton(self.layoutWidget3)
        self.pushButton_ResetSaftyChain.setEnabled(False)
        self.pushButton_ResetSaftyChain.setObjectName(_fromUtf8("pushButton_ResetSaftyChain"))
        self.gridLayout_2.addWidget(self.pushButton_ResetSaftyChain, 0, 2, 1, 1)              
        #bplevel
        self.label_bp = QLabel(self.layoutWidget3)
        self.label_bp.setObjectName(_fromUtf8("label_bp"))
        self.gridLayout_2.addWidget(self.label_bp, 1, 0, 1, 1)        
        self.pushButton_bp50 = QPushButton(self.layoutWidget3)
        self.pushButton_bp50.setEnabled(False)
        self.pushButton_bp50.setObjectName(_fromUtf8("pushButton_bp50"))
        self.gridLayout_2.addWidget(self.pushButton_bp50, 1, 1, 1, 1)
        self.pushButton_bp51 = QPushButton(self.layoutWidget3)
        self.pushButton_bp51.setEnabled(False)
        self.pushButton_bp51.setObjectName(_fromUtf8("pushButton_bp51"))
        self.gridLayout_2.addWidget(self.pushButton_bp51, 1, 2, 1, 1)      
        self.pushButton_bp100 = QPushButton(self.layoutWidget3)
        self.pushButton_bp100.setEnabled(False)
        self.pushButton_bp100.setObjectName(_fromUtf8("pushButton_bp100"))
        self.gridLayout_2.addWidget(self.pushButton_bp100, 1, 3, 1, 1)
        self.pushButton_bp150 = QPushButton(self.layoutWidget3)
        self.pushButton_bp150.setEnabled(False)
        self.pushButton_bp150.setObjectName(_fromUtf8("pushButton_bp150"))        
        self.gridLayout_2.addWidget(self.pushButton_bp150, 1, 4, 1, 1)  
        self.pushButton_bp199 = QPushButton(self.layoutWidget3)
        self.pushButton_bp199.setEnabled(False)
        self.pushButton_bp199.setObjectName(_fromUtf8("pushButton_bp199"))
        self.gridLayout_2.addWidget(self.pushButton_bp199, 2, 1, 1, 1)  
        #test
        self.label_test = QLabel(self.layoutWidget3)
        self.label_test.setObjectName(_fromUtf8("label_test"))
        self.gridLayout_2.addWidget(self.label_test, 3, 0, 1, 1)
        self.pushButton_highwind = QPushButton(self.layoutWidget3)
        self.pushButton_highwind.setEnabled(False)
        self.pushButton_highwind.setObjectName(_fromUtf8("pushButton_highwind"))
        self.gridLayout_2.addWidget(self.pushButton_highwind, 3, 1, 1, 1)
        self.pushButton_limitPower = QPushButton(self.layoutWidget3)
        self.pushButton_limitPower.setEnabled(False)
        self.pushButton_limitPower.setObjectName(_fromUtf8("pushButton_limitPower"))
        self.gridLayout_2.addWidget(self.pushButton_limitPower, 3, 2, 1, 1)    
        self.pushButton_highwindStop = QPushButton(self.layoutWidget3)
        self.pushButton_highwindStop.setEnabled(False)
        self.pushButton_highwindStop.setObjectName(_fromUtf8("pushButton_highwindStop"))        
        self.gridLayout_2.addWidget(self.pushButton_highwindStop, 3, 3, 1, 1)
        self.pushButton_lowwind = QPushButton(self.layoutWidget3)
        self.pushButton_lowwind.setEnabled(False)
        self.pushButton_lowwind.setObjectName(_fromUtf8("pushButton_lowwind"))
        self.gridLayout_2.addWidget(self.pushButton_lowwind, 3, 4, 1, 1)      
        self.pushButton_lowwindStop = QPushButton(self.layoutWidget3)
        self.pushButton_lowwindStop.setEnabled(False)
        self.pushButton_lowwindStop.setObjectName(_fromUtf8("pushButton_lowwindStop"))
        self.gridLayout_2.addWidget(self.pushButton_lowwindStop, 4, 1, 1, 1)      
        
        self.pushButton_traclogDone = QPushButton(self.layoutWidget3)
        self.pushButton_traclogDone.setEnabled(False)
        self.pushButton_traclogDone.setObjectName(_fromUtf8("pushButton_traclogDone"))
        self.gridLayout_2.addWidget(self.pushButton_traclogDone, 4, 2, 1, 1)                 

        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_16 = QLabel(self.tab)
        self.label_16.setGeometry(QRect(460, 60, 101, 71))
        self.label_16.setAutoFillBackground(False)
        self.label_16.setTextFormat(Qt.AutoText)
        self.label_16.setScaledContents(False)
        self.label_16.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.label_16.setWordWrap(False)
        self.label_16.setTextInteractionFlags(Qt.NoTextInteraction)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.layoutWidget4 = QWidget(self.tab)
        self.layoutWidget4.setGeometry(QRect(30, 260, 171, 61))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.gridLayout_3 = QGridLayout(self.layoutWidget4)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_21 = QLabel(self.layoutWidget4)
        self.label_21.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.label_21.setWordWrap(False)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_3.addWidget(self.label_21, 0, 2, 1, 1)
        self.label_22 = QLabel(self.layoutWidget4)
        self.label_22.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.label_22.setWordWrap(False)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_3.addWidget(self.label_22, 1, 2, 1, 1)
        self.lineEdit_long_recorder = QLineEdit(self.layoutWidget4)
        self.lineEdit_long_recorder.setObjectName(_fromUtf8("lineEdit_long_recorder"))
        self.gridLayout_3.addWidget(self.lineEdit_long_recorder, 1, 1, 1, 1)
        self.label_17 = QLabel(self.layoutWidget4)
        self.label_17.setLayoutDirection(Qt.LeftToRight)
        self.label_17.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_3.addWidget(self.label_17, 0, 0, 1, 1)
        self.lineEdit_ter_recorder = QLineEdit(self.layoutWidget4)
        self.lineEdit_ter_recorder.setObjectName(_fromUtf8("lineEdit_ter_recorder"))
        self.gridLayout_3.addWidget(self.lineEdit_ter_recorder, 0, 1, 1, 1)
        self.label_18 = QLabel(self.layoutWidget4)
        self.label_18.setLayoutDirection(Qt.LeftToRight)
        self.label_18.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_3.addWidget(self.label_18, 1, 0, 1, 1)
        self.layoutWidget5 = QWidget(self.tab)
        self.layoutWidget5.setGeometry(QRect(30, 20, 391, 221))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.gridLayout_4 = QGridLayout(self.layoutWidget5)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lineEdit_ip_recorder = QLineEdit(self.layoutWidget5)
        self.lineEdit_ip_recorder.setEnabled(False)
        self.lineEdit_ip_recorder.setMaximumSize(QSize(180, 16777215))
        self.lineEdit_ip_recorder.setObjectName(_fromUtf8("lineEdit_ip_recorder"))
        self.gridLayout_4.addWidget(self.lineEdit_ip_recorder, 0, 1, 1, 1)
        self.label_14 = QLabel(self.layoutWidget5)
        self.label_14.setLayoutDirection(Qt.LeftToRight)
        self.label_14.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_4.addWidget(self.label_14, 0, 0, 1, 1)
        self.textEdit_var_recorder = QTextEdit(self.layoutWidget5)
        self.textEdit_var_recorder.setObjectName(_fromUtf8("textEdit_var_recorder"))
        self.gridLayout_4.addWidget(self.textEdit_var_recorder, 1, 1, 1, 1)
        self.label_15 = QLabel(self.layoutWidget5)
        self.label_15.setLayoutDirection(Qt.LeftToRight)
        self.label_15.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_4.addWidget(self.label_15, 1, 0, 1, 1)
        self.layoutWidget6 = QWidget(self.tab)
        self.layoutWidget6.setGeometry(QRect(270, 250, 121, 110))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.verticalLayout = QVBoxLayout(self.layoutWidget6)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButton_savevar = QPushButton(self.layoutWidget6)
        self.pushButton_savevar.setObjectName(_fromUtf8("pushButton_savevar"))
        self.verticalLayout.addWidget(self.pushButton_savevar)
        self.pushButton_startRecorder = QPushButton(self.layoutWidget6)
        self.pushButton_startRecorder.setEnabled(False)
        self.pushButton_startRecorder.setObjectName(_fromUtf8("pushButton_startRecorder"))
        self.verticalLayout.addWidget(self.pushButton_startRecorder)
        self.pushButton_stopRecorder = QPushButton(self.layoutWidget6)
        self.pushButton_stopRecorder.setEnabled(False)
        self.pushButton_stopRecorder.setObjectName(_fromUtf8("pushButton_stopRecorder"))
        self.verticalLayout.addWidget(self.pushButton_stopRecorder)
        
        self.pushButton_openFileDir = QPushButton(self.layoutWidget6)
        self.pushButton_openFileDir.setEnabled(True)
        self.pushButton_openFileDir.setObjectName(_fromUtf8("pushButton_openFileDir"))
        self.verticalLayout.addWidget(self.pushButton_openFileDir)
        
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.checkBox_turbineOP = QCheckBox(self.centralwidget)
        self.checkBox_turbineOP.setEnabled(False)
        self.checkBox_turbineOP.setGeometry(QRect(10, 440, 111, 16))
        self.checkBox_turbineOP.setObjectName(_fromUtf8("checkBox_turbineOP"))
        self.pushButton_SClist = QPushButton(self.centralwidget)
        self.pushButton_SClist.setEnabled(False)
        self.pushButton_SClist.setGeometry(QRect(530, 440, 75, 23))
        self.pushButton_SClist.setObjectName(_fromUtf8("pushButton_SClist"))

        self.layoutWidget7 = QWidget(self.centralwidget)
        self.layoutWidget7.setGeometry(QRect(10, 470, 611, 21))
        self.layoutWidget7.setObjectName(_fromUtf8("layoutWidget7"))
        self.horizontalLayout = QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_power = QLabel(self.layoutWidget7)
        self.label_power.setObjectName(_fromUtf8("label_power"))
        self.horizontalLayout.addWidget(self.label_power)
        self.label_genspeed = QLabel(self.layoutWidget7)
        self.label_genspeed.setObjectName(_fromUtf8("label_genspeed"))
        self.horizontalLayout.addWidget(self.label_genspeed)
        self.label_windspeed = QLabel(self.layoutWidget7)
        self.label_windspeed.setObjectName(_fromUtf8("label_windspeed"))
        self.horizontalLayout.addWidget(self.label_windspeed)
        self.label_turbineOP = QLabel(self.layoutWidget7)
        self.label_turbineOP.setObjectName(_fromUtf8("label_turbineOP"))
        self.horizontalLayout.addWidget(self.label_turbineOP)
        self.label_bplevel = QLabel(self.layoutWidget7)
        self.label_bplevel.setObjectName(_fromUtf8("label_bplevel"))
        self.horizontalLayout.addWidget(self.label_bplevel)
        self.label_yplevel = QLabel(self.layoutWidget7)
        self.label_yplevel.setObjectName(_fromUtf8("label_yplevel"))
        self.horizontalLayout.addWidget(self.label_yplevel)
        O2Tool.setCentralWidget(self.centralwidget)

        #新增批量读批量写
        self.tab_BatchRead = QWidget()
        self.tab_BatchRead.setObjectName(_fromUtf8("tab_BatchRead"))
        self.layoutWidget7 = QWidget(self.tab_BatchRead)
        self.layoutWidget7.setGeometry(QRect(20, 10, 571, 373))
        self.layoutWidget7.setObjectName(_fromUtf8("layoutWidget7"))
        self.gridLayout_6 = QGridLayout(self.layoutWidget7)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_7 = QLabel(self.layoutWidget7)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QSize(0, 0))
        self.label_7.setMaximumSize(QSize(80, 16777215))
        self.label_7.setLayoutDirection(Qt.LeftToRight)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_6.addWidget(self.label_7, 1, 0, 1, 1)
        self.comboBox_batchVar1 = QComboBox(self.layoutWidget7)
        self.comboBox_batchVar1.setEditable(True)
        self.comboBox_batchVar1.setObjectName(_fromUtf8("comboBox_batchVar1"))
        self.gridLayout_6.addWidget(self.comboBox_batchVar1, 1, 1, 1, 1)
        self.pushButton_batchRead1 = QPushButton(self.layoutWidget7)
        self.pushButton_batchRead1.setEnabled(False)
        self.pushButton_batchRead1.setMaximumSize(QSize(80, 16777215))
        self.pushButton_batchRead1.setObjectName(_fromUtf8("pushButton_batchRead1"))
        self.gridLayout_6.addWidget(self.pushButton_batchRead1, 1, 3, 1, 1)
        self.pushButton_batchWrite1 = QPushButton(self.layoutWidget7)
        self.pushButton_batchWrite1.setEnabled(False)
        self.pushButton_batchWrite1.setMaximumSize(QSize(80, 16777215))
        self.pushButton_batchWrite1.setObjectName(_fromUtf8("pushButton_batchWrite1"))
        self.gridLayout_6.addWidget(self.pushButton_batchWrite1, 1, 4, 1, 1)
        self.label_28 = QLabel(self.layoutWidget7)
        self.label_28.setLayoutDirection(Qt.LeftToRight)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_6.addWidget(self.label_28, 2, 0, 1, 1)
        self.comboBox_batchVar2 = QComboBox(self.layoutWidget7)
        self.comboBox_batchVar2.setEditable(True)
        self.comboBox_batchVar2.setObjectName(_fromUtf8("comboBox_batchVar2"))
        self.gridLayout_6.addWidget(self.comboBox_batchVar2, 2, 1, 1, 1)
        self.pushButton_batchRead2 = QPushButton(self.layoutWidget7)
        self.pushButton_batchRead2.setEnabled(False)
        self.pushButton_batchRead2.setObjectName(_fromUtf8("pushButton_batchRead2"))
        self.gridLayout_6.addWidget(self.pushButton_batchRead2, 2, 3, 1, 1)
        self.pushButton_batchWrite2 = QPushButton(self.layoutWidget7)
        self.pushButton_batchWrite2.setEnabled(False)
        self.pushButton_batchWrite2.setObjectName(_fromUtf8("pushButton_batchWrite2"))
        self.gridLayout_6.addWidget(self.pushButton_batchWrite2, 2, 4, 1, 1)
        self.label_29 = QLabel(self.layoutWidget7)
        self.label_29.setLayoutDirection(Qt.LeftToRight)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_6.addWidget(self.label_29, 3, 0, 1, 1)
        self.comboBox_batchVar3 = QComboBox(self.layoutWidget7)
        self.comboBox_batchVar3.setEditable(True)
        self.comboBox_batchVar3.setObjectName(_fromUtf8("comboBox_batchVar3"))
        self.gridLayout_6.addWidget(self.comboBox_batchVar3, 3, 1, 1, 1)
        self.pushButton_batchRead3 = QPushButton(self.layoutWidget7)
        self.pushButton_batchRead3.setEnabled(False)
        self.pushButton_batchRead3.setObjectName(_fromUtf8("pushButton_batchRead3"))
        self.gridLayout_6.addWidget(self.pushButton_batchRead3, 3, 3, 1, 1)
        self.pushButton_batchWrite3 = QPushButton(self.layoutWidget7)
        self.pushButton_batchWrite3.setEnabled(False)
        self.pushButton_batchWrite3.setObjectName(_fromUtf8("pushButton_batchWrite3"))
        self.gridLayout_6.addWidget(self.pushButton_batchWrite3, 3, 4, 1, 1)
        self.label_30 = QLabel(self.layoutWidget7)
        self.label_30.setLayoutDirection(Qt.LeftToRight)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_6.addWidget(self.label_30, 4, 0, 1, 1)
        self.comboBox_batchVar4 = QComboBox(self.layoutWidget7)
        self.comboBox_batchVar4.setEditable(True)
        self.comboBox_batchVar4.setObjectName(_fromUtf8("comboBox_batchVar4"))
        self.gridLayout_6.addWidget(self.comboBox_batchVar4, 4, 1, 1, 1)
        self.pushButton_batchRead4 = QPushButton(self.layoutWidget7)
        self.pushButton_batchRead4.setEnabled(False)
        self.pushButton_batchRead4.setObjectName(_fromUtf8("pushButton_batchRead4"))
        self.gridLayout_6.addWidget(self.pushButton_batchRead4, 4, 3, 1, 1)
        self.pushButton_batchWrite4 = QPushButton(self.layoutWidget7)
        self.pushButton_batchWrite4.setEnabled(False)
        self.pushButton_batchWrite4.setObjectName(_fromUtf8("pushButton_batchWrite4"))
        self.gridLayout_6.addWidget(self.pushButton_batchWrite4, 4, 4, 1, 1)
        self.label_34 = QLabel(self.layoutWidget7)
        self.label_34.setLayoutDirection(Qt.LeftToRight)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_6.addWidget(self.label_34, 5, 0, 1, 1)
        self.comboBox_batchVar5 = QComboBox(self.layoutWidget7)
        self.comboBox_batchVar5.setEditable(True)
        self.comboBox_batchVar5.setObjectName(_fromUtf8("comboBox_batchVar5"))
        self.gridLayout_6.addWidget(self.comboBox_batchVar5, 5, 1, 1, 1)
        self.pushButton_batchRead5 = QPushButton(self.layoutWidget7)
        self.pushButton_batchRead5.setEnabled(False)
        self.pushButton_batchRead5.setObjectName(_fromUtf8("pushButton_batchRead5"))
        self.gridLayout_6.addWidget(self.pushButton_batchRead5, 5, 3, 1, 1)
        self.pushButton_batchWrite5 = QPushButton(self.layoutWidget7)
        self.pushButton_batchWrite5.setEnabled(False)
        self.pushButton_batchWrite5.setObjectName(_fromUtf8("pushButton_batchWrite5"))
        self.gridLayout_6.addWidget(self.pushButton_batchWrite5, 5, 4, 1, 1)
        self.label_31 = QLabel(self.layoutWidget7)
        self.label_31.setLayoutDirection(Qt.LeftToRight)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_6.addWidget(self.label_31, 6, 0, 1, 1)
        self.comboBox_batchVar6 = QComboBox(self.layoutWidget7)
        self.comboBox_batchVar6.setEditable(True)
        self.comboBox_batchVar6.setObjectName(_fromUtf8("comboBox_batchVar6"))
        self.gridLayout_6.addWidget(self.comboBox_batchVar6, 6, 1, 1, 1)
        self.pushButton_batchRead6 = QPushButton(self.layoutWidget7)
        self.pushButton_batchRead6.setEnabled(False)
        self.pushButton_batchRead6.setObjectName(_fromUtf8("pushButton_batchRead6"))
        self.gridLayout_6.addWidget(self.pushButton_batchRead6, 6, 3, 1, 1)
        self.pushButton_batchWrite6 = QPushButton(self.layoutWidget7)
        self.pushButton_batchWrite6.setEnabled(False)
        self.pushButton_batchWrite6.setObjectName(_fromUtf8("pushButton_batchWrite6"))
        self.gridLayout_6.addWidget(self.pushButton_batchWrite6, 6, 4, 1, 1)
        self.label_32 = QLabel(self.layoutWidget7)
        self.label_32.setLayoutDirection(Qt.LeftToRight)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_6.addWidget(self.label_32, 7, 0, 1, 1)
        self.comboBox_batchVar7 = QComboBox(self.layoutWidget7)
        self.comboBox_batchVar7.setEditable(True)
        self.comboBox_batchVar7.setObjectName(_fromUtf8("comboBox_batchVar7"))
        self.gridLayout_6.addWidget(self.comboBox_batchVar7, 7, 1, 1, 1)
        self.pushButton_batchRead7 = QPushButton(self.layoutWidget7)
        self.pushButton_batchRead7.setEnabled(False)
        self.pushButton_batchRead7.setObjectName(_fromUtf8("pushButton_batchRead7"))
        self.gridLayout_6.addWidget(self.pushButton_batchRead7, 7, 3, 1, 1)
        self.pushButton_batchWrite7 = QPushButton(self.layoutWidget7)
        self.pushButton_batchWrite7.setEnabled(False)
        self.pushButton_batchWrite7.setObjectName(_fromUtf8("pushButton_batchWrite7"))
        self.gridLayout_6.addWidget(self.pushButton_batchWrite7, 7, 4, 1, 1)
        self.label_33 = QLabel(self.layoutWidget7)
        self.label_33.setLayoutDirection(Qt.LeftToRight)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_6.addWidget(self.label_33, 8, 0, 1, 1)
        self.comboBox_batchVar8 = QComboBox(self.layoutWidget7)
        self.comboBox_batchVar8.setEditable(True)
        self.comboBox_batchVar8.setObjectName(_fromUtf8("comboBox_batchVar8"))
        self.gridLayout_6.addWidget(self.comboBox_batchVar8, 8, 1, 1, 1)
        self.pushButton_batchRead8 = QPushButton(self.layoutWidget7)
        self.pushButton_batchRead8.setEnabled(False)
        self.pushButton_batchRead8.setObjectName(_fromUtf8("pushButton_batchRead8"))
        self.gridLayout_6.addWidget(self.pushButton_batchRead8, 8, 3, 1, 1)
        self.pushButton_batchWrite8 = QPushButton(self.layoutWidget7)
        self.pushButton_batchWrite8.setEnabled(False)
        self.pushButton_batchWrite8.setObjectName(_fromUtf8("pushButton_batchWrite8"))
        self.gridLayout_6.addWidget(self.pushButton_batchWrite8, 8, 4, 1, 1)
        self.label_38 = QLabel(self.layoutWidget7)
        self.label_38.setLayoutDirection(Qt.LeftToRight)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_6.addWidget(self.label_38, 9, 0, 1, 1)
        self.comboBox_batchVar9 = QComboBox(self.layoutWidget7)
        self.comboBox_batchVar9.setEditable(True)
        self.comboBox_batchVar9.setObjectName(_fromUtf8("comboBox_batchVar9"))
        self.gridLayout_6.addWidget(self.comboBox_batchVar9, 9, 1, 1, 1)
        self.pushButton_batchRead9 = QPushButton(self.layoutWidget7)
        self.pushButton_batchRead9.setEnabled(False)
        self.pushButton_batchRead9.setObjectName(_fromUtf8("pushButton_batchRead9"))
        self.gridLayout_6.addWidget(self.pushButton_batchRead9, 9, 3, 1, 1)
        self.pushButton_batchWrite9 = QPushButton(self.layoutWidget7)
        self.pushButton_batchWrite9.setEnabled(False)
        self.pushButton_batchWrite9.setObjectName(_fromUtf8("pushButton_batchWrite9"))
        self.gridLayout_6.addWidget(self.pushButton_batchWrite9, 9, 4, 1, 1)
        self.label_35 = QLabel(self.layoutWidget7)
        self.label_35.setLayoutDirection(Qt.LeftToRight)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_6.addWidget(self.label_35, 10, 0, 1, 1)
        self.comboBox_batchVar10 = QComboBox(self.layoutWidget7)
        self.comboBox_batchVar10.setEditable(True)
        self.comboBox_batchVar10.setObjectName(_fromUtf8("comboBox_batchVar10"))
        self.gridLayout_6.addWidget(self.comboBox_batchVar10, 10, 1, 1, 1)
        self.pushButton_batchRead10 = QPushButton(self.layoutWidget7)
        self.pushButton_batchRead10.setEnabled(False)
        self.pushButton_batchRead10.setObjectName(_fromUtf8("pushButton_batchRead10"))
        self.gridLayout_6.addWidget(self.pushButton_batchRead10, 10, 3, 1, 1)
        self.pushButton_batchWrite10 = QPushButton(self.layoutWidget7)
        self.pushButton_batchWrite10.setEnabled(False)
        self.pushButton_batchWrite10.setObjectName(_fromUtf8("pushButton_batchWrite10"))
        self.gridLayout_6.addWidget(self.pushButton_batchWrite10, 10, 4, 1, 1)
        self.label_36 = QLabel(self.layoutWidget7)
        self.label_36.setLayoutDirection(Qt.LeftToRight)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_6.addWidget(self.label_36, 11, 0, 1, 1)
        self.comboBox_batchVar11 = QComboBox(self.layoutWidget7)
        self.comboBox_batchVar11.setEditable(True)
        self.comboBox_batchVar11.setObjectName(_fromUtf8("comboBox_batchVar11"))
        self.gridLayout_6.addWidget(self.comboBox_batchVar11, 11, 1, 1, 1)
        self.pushButton_batchRead11 = QPushButton(self.layoutWidget7)
        self.pushButton_batchRead11.setEnabled(False)
        self.pushButton_batchRead11.setObjectName(_fromUtf8("pushButton_batchRead11"))
        self.gridLayout_6.addWidget(self.pushButton_batchRead11, 11, 3, 1, 1)
        self.pushButton_batchWrite11 = QPushButton(self.layoutWidget7)
        self.pushButton_batchWrite11.setEnabled(False)
        self.pushButton_batchWrite11.setObjectName(_fromUtf8("pushButton_batchWrite11"))
        self.gridLayout_6.addWidget(self.pushButton_batchWrite11, 11, 4, 1, 1)
        self.label_37 = QLabel(self.layoutWidget7)
        self.label_37.setLayoutDirection(Qt.LeftToRight)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_6.addWidget(self.label_37, 12, 0, 1, 1)
        self.comboBox_batchVar12 = QComboBox(self.layoutWidget7)
        self.comboBox_batchVar12.setEditable(True)
        self.comboBox_batchVar12.setObjectName(_fromUtf8("comboBox_batchVar12"))
        self.gridLayout_6.addWidget(self.comboBox_batchVar12, 12, 1, 1, 1)
        self.pushButton_batchRead12 = QPushButton(self.layoutWidget7)
        self.pushButton_batchRead12.setEnabled(False)
        self.pushButton_batchRead12.setObjectName(_fromUtf8("pushButton_batchRead12"))
        self.gridLayout_6.addWidget(self.pushButton_batchRead12, 12, 3, 1, 1)
        self.pushButton_batchWrite12 = QPushButton(self.layoutWidget7)
        self.pushButton_batchWrite12.setEnabled(False)
        self.pushButton_batchWrite12.setObjectName(_fromUtf8("pushButton_batchWrite12"))
        self.gridLayout_6.addWidget(self.pushButton_batchWrite12, 12, 4, 1, 1)
        self.lineEdit_batchValue_1 = QLineEdit(self.layoutWidget7)
        self.lineEdit_batchValue_1.setEnabled(True)
        self.lineEdit_batchValue_1.setMaximumSize(QSize(80, 16777215))
        self.lineEdit_batchValue_1.setText(_fromUtf8(""))
        self.lineEdit_batchValue_1.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineEdit_batchValue_1.setObjectName(_fromUtf8("lineEdit_batchValue_1"))
        self.gridLayout_6.addWidget(self.lineEdit_batchValue_1, 1, 2, 1, 1)
        self.lineEdit_batchValue_2 = QLineEdit(self.layoutWidget7)
        self.lineEdit_batchValue_2.setEnabled(True)
        self.lineEdit_batchValue_2.setMaximumSize(QSize(80, 16777215))
        self.lineEdit_batchValue_2.setText(_fromUtf8(""))
        self.lineEdit_batchValue_2.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineEdit_batchValue_2.setObjectName(_fromUtf8("lineEdit_batchValue_2"))
        self.gridLayout_6.addWidget(self.lineEdit_batchValue_2, 2, 2, 1, 1)
        self.lineEdit_batchValue_3 = QLineEdit(self.layoutWidget7)
        self.lineEdit_batchValue_3.setEnabled(True)
        self.lineEdit_batchValue_3.setMaximumSize(QSize(80, 16777215))
        self.lineEdit_batchValue_3.setText(_fromUtf8(""))
        self.lineEdit_batchValue_3.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineEdit_batchValue_3.setObjectName(_fromUtf8("lineEdit_batchValue_3"))
        self.gridLayout_6.addWidget(self.lineEdit_batchValue_3, 3, 2, 1, 1)
        self.lineEdit_batchValue_4 = QLineEdit(self.layoutWidget7)
        self.lineEdit_batchValue_4.setEnabled(True)
        self.lineEdit_batchValue_4.setMaximumSize(QSize(80, 16777215))
        self.lineEdit_batchValue_4.setText(_fromUtf8(""))
        self.lineEdit_batchValue_4.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineEdit_batchValue_4.setObjectName(_fromUtf8("lineEdit_batchValue_4"))
        self.gridLayout_6.addWidget(self.lineEdit_batchValue_4, 4, 2, 1, 1)
        self.lineEdit_batchValue_5 = QLineEdit(self.layoutWidget7)
        self.lineEdit_batchValue_5.setEnabled(True)
        self.lineEdit_batchValue_5.setMaximumSize(QSize(80, 16777215))
        self.lineEdit_batchValue_5.setText(_fromUtf8(""))
        self.lineEdit_batchValue_5.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineEdit_batchValue_5.setObjectName(_fromUtf8("lineEdit_batchValue_5"))
        self.gridLayout_6.addWidget(self.lineEdit_batchValue_5, 5, 2, 1, 1)
        self.lineEdit_batchValue_6 = QLineEdit(self.layoutWidget7)
        self.lineEdit_batchValue_6.setEnabled(True)
        self.lineEdit_batchValue_6.setMaximumSize(QSize(80, 16777215))
        self.lineEdit_batchValue_6.setText(_fromUtf8(""))
        self.lineEdit_batchValue_6.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineEdit_batchValue_6.setObjectName(_fromUtf8("lineEdit_batchValue_6"))
        self.gridLayout_6.addWidget(self.lineEdit_batchValue_6, 6, 2, 1, 1)
        self.lineEdit_batchValue_7 = QLineEdit(self.layoutWidget7)
        self.lineEdit_batchValue_7.setEnabled(True)
        self.lineEdit_batchValue_7.setMaximumSize(QSize(80, 16777215))
        self.lineEdit_batchValue_7.setText(_fromUtf8(""))
        self.lineEdit_batchValue_7.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineEdit_batchValue_7.setObjectName(_fromUtf8("lineEdit_batchValue_7"))
        self.gridLayout_6.addWidget(self.lineEdit_batchValue_7, 7, 2, 1, 1)
        self.lineEdit_batchValue_8 = QLineEdit(self.layoutWidget7)
        self.lineEdit_batchValue_8.setEnabled(True)
        self.lineEdit_batchValue_8.setMaximumSize(QSize(80, 16777215))
        self.lineEdit_batchValue_8.setText(_fromUtf8(""))
        self.lineEdit_batchValue_8.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineEdit_batchValue_8.setObjectName(_fromUtf8("lineEdit_batchValue_8"))
        self.gridLayout_6.addWidget(self.lineEdit_batchValue_8, 8, 2, 1, 1)
        self.lineEdit_batchValue_9 = QLineEdit(self.layoutWidget7)
        self.lineEdit_batchValue_9.setEnabled(True)
        self.lineEdit_batchValue_9.setMaximumSize(QSize(80, 16777215))
        self.lineEdit_batchValue_9.setText(_fromUtf8(""))
        self.lineEdit_batchValue_9.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineEdit_batchValue_9.setObjectName(_fromUtf8("lineEdit_batchValue_9"))
        self.gridLayout_6.addWidget(self.lineEdit_batchValue_9, 9, 2, 1, 1)
        self.lineEdit_batchValue_10 = QLineEdit(self.layoutWidget7)
        self.lineEdit_batchValue_10.setEnabled(True)
        self.lineEdit_batchValue_10.setMaximumSize(QSize(80, 16777215))
        self.lineEdit_batchValue_10.setText(_fromUtf8(""))
        self.lineEdit_batchValue_10.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineEdit_batchValue_10.setObjectName(_fromUtf8("lineEdit_batchValue_10"))
        self.gridLayout_6.addWidget(self.lineEdit_batchValue_10, 10, 2, 1, 1)
        self.lineEdit_batchValue_11 = QLineEdit(self.layoutWidget7)
        self.lineEdit_batchValue_11.setEnabled(True)
        self.lineEdit_batchValue_11.setMaximumSize(QSize(80, 16777215))
        self.lineEdit_batchValue_11.setText(_fromUtf8(""))
        self.lineEdit_batchValue_11.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineEdit_batchValue_11.setObjectName(_fromUtf8("lineEdit_batchValue_11"))
        self.gridLayout_6.addWidget(self.lineEdit_batchValue_11, 11, 2, 1, 1)
        self.lineEdit_batchValue_12 = QLineEdit(self.layoutWidget7)
        self.lineEdit_batchValue_12.setEnabled(True)
        self.lineEdit_batchValue_12.setMaximumSize(QSize(80, 16777215))
        self.lineEdit_batchValue_12.setText(_fromUtf8(""))
        self.lineEdit_batchValue_12.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineEdit_batchValue_12.setObjectName(_fromUtf8("lineEdit_batchValue_12"))
        self.gridLayout_6.addWidget(self.lineEdit_batchValue_12, 12, 2, 1, 1)
        self.label_41 = QLabel(self.layoutWidget7)
        self.label_41.setLayoutDirection(Qt.LeftToRight)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_6.addWidget(self.label_41, 0, 0, 1, 1)
        self.lineEdit_ip_batchRead = QLineEdit(self.layoutWidget7)
        self.lineEdit_ip_batchRead.setEnabled(False)
        self.lineEdit_ip_batchRead.setMaximumSize(QSize(180, 16777215))
        self.lineEdit_ip_batchRead.setObjectName(_fromUtf8("lineEdit_ip_batchRead"))
        self.gridLayout_6.addWidget(self.lineEdit_ip_batchRead, 0, 1, 1, 1)
        self.pushButton_batchReadAll = QPushButton(self.layoutWidget7)
        self.pushButton_batchReadAll.setEnabled(False)
        self.pushButton_batchReadAll.setMaximumSize(QSize(80, 16777215))
        self.pushButton_batchReadAll.setObjectName(_fromUtf8("pushButton_batchReadAll"))
        self.gridLayout_6.addWidget(self.pushButton_batchReadAll, 0, 3, 1, 1)
        self.tabWidget.addTab(self.tab_BatchRead, _fromUtf8(""))
        self.pushButton_batchWriteAll = QPushButton(self.layoutWidget7)
        self.pushButton_batchWriteAll.setEnabled(False)
        self.pushButton_batchWriteAll.setMaximumSize(QSize(80, 16777215))
        self.pushButton_batchWriteAll.setObjectName(_fromUtf8("pushButton_batchWriteAll"))
        self.pushButton_batchConnect = QPushButton(self.layoutWidget7)
        self.pushButton_batchConnect.setMaximumSize(QSize(80, 16777215))
        self.pushButton_batchConnect.setObjectName(_fromUtf8("pushButton_batchConnect"))
        self.gridLayout_6.addWidget(self.pushButton_batchConnect, 0, 2, 1, 1)
        
        
        self.gridLayout_6.addWidget(self.pushButton_batchWriteAll, 0, 4, 1, 1)  
        self.tab_BatchWrite = QWidget()
        self.tab_BatchWrite.setObjectName(_fromUtf8("tab_BatchWrite"))
        self.pushButton_batchCheck = QPushButton(self.tab_BatchWrite)
        self.pushButton_batchCheck.setGeometry(QRect(460, 140, 80, 23))
        self.pushButton_batchCheck.setMaximumSize(QSize(80, 16777215))
        self.pushButton_batchCheck.setObjectName(_fromUtf8("pushButton_batchCheck"))
        self.pushButton_batchWrite = QPushButton(self.tab_BatchWrite)
        self.pushButton_batchWrite.setEnabled(False)
        self.pushButton_batchWrite.setGeometry(QRect(460, 180, 80, 23))
        self.pushButton_batchWrite.setMaximumSize(QSize(80, 16777215))
        self.pushButton_batchWrite.setObjectName(_fromUtf8("pushButton_batchWrite"))
        self.pushButton_batchClean = QPushButton(self.tab_BatchWrite)

        self.pushButton_batchClean.setGeometry(QRect(460, 290, 80, 23))
        self.pushButton_batchClean.setMaximumSize(QSize(80, 16777215))
        self.pushButton_batchClean.setObjectName(_fromUtf8("pushButton_batchClean"))
        self.label_finished = QLabel(self.tab_BatchWrite)
        self.label_finished.setGeometry(QRect(460, 220, 121, 51))
        self.label_finished.setLayoutDirection(Qt.LeftToRight)
        self.label_finished.setText(_fromUtf8(""))
        self.label_finished.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.label_finished.setWordWrap(True)
        self.label_finished.setTextInteractionFlags(Qt.NoTextInteraction)
        self.label_finished.setObjectName(_fromUtf8("label_finished"))
        self.lineEdit_ip_batch = QLineEdit(self.tab_BatchWrite)
        self.lineEdit_ip_batch.setEnabled(False)
        self.lineEdit_ip_batch.setGeometry(QRect(130, 20, 180, 20))
        #self.lineEdit_ip_batch.setMaximumSize(QSize(180, 16777215))
        self.lineEdit_ip_batch.setObjectName(_fromUtf8("lineEdit_ip_batch"))
        self.textEdit_var_batchWrite = QTextEdit(self.tab_BatchWrite)
        self.textEdit_var_batchWrite.setGeometry(QRect(50, 80, 381, 281))
        self.textEdit_var_batchWrite.setObjectName(_fromUtf8("textEdit_var_batchWrite"))
        self.label_39 = QLabel(self.tab_BatchWrite)
        self.label_39.setGeometry(QRect(40, 20, 84, 16))
        self.label_39.setLayoutDirection(Qt.LeftToRight)
        self.label_39.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.label_40 = QLabel(self.tab_BatchWrite)
        self.label_40.setGeometry(QRect(41, 57, 54, 16))
        self.label_40.setLayoutDirection(Qt.LeftToRight)
        self.label_40.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.tabWidget.addTab(self.tab_BatchWrite, _fromUtf8(""))      
        
        
        
    
        self.retranslateUi(O2Tool)
        self.tabWidget.setCurrentIndex(0)
        QMetaObject.connectSlotsByName(O2Tool)
        O2Tool.setTabOrder(self.comboBox_ip, self.lineEdit_port)
        O2Tool.setTabOrder(self.lineEdit_port, self.pushButton_adsConnect)
        O2Tool.setTabOrder(self.pushButton_adsConnect, self.comboBox_name)
        O2Tool.setTabOrder(self.comboBox_name, self.pushButton_adsLoad)
        O2Tool.setTabOrder(self.pushButton_adsLoad, self.lineEdit_type)
        O2Tool.setTabOrder(self.lineEdit_type, self.lineEdit_value)
        O2Tool.setTabOrder(self.lineEdit_value, self.pushButton_adsTrigger)
        O2Tool.setTabOrder(self.pushButton_adsTrigger, self.lineEdit_set)
        O2Tool.setTabOrder(self.lineEdit_set, self.pushButton_adsWrite)
        O2Tool.setTabOrder(self.pushButton_adsWrite, self.lineEdit_windspeed)
        O2Tool.setTabOrder(self.lineEdit_windspeed, self.pushButton_setWindspeed)
        O2Tool.setTabOrder(self.pushButton_setWindspeed, self.pushButton_loadWindspeed)
        O2Tool.setTabOrder(self.pushButton_loadWindspeed, self.lineEdit_Scada)
        O2Tool.setTabOrder(self.lineEdit_Scada, self.pushButton_setScada)
        O2Tool.setTabOrder(self.pushButton_setScada, self.pushButton_resetScada)
        O2Tool.setTabOrder(self.pushButton_resetScada, self.pushButton_loadScada)
        O2Tool.setTabOrder(self.pushButton_loadScada, self.lineEdit_Radius)
        O2Tool.setTabOrder(self.lineEdit_Radius, self.pushButton_setRadius)
        O2Tool.setTabOrder(self.pushButton_setRadius, self.pushButton_loadRadius)
        O2Tool.setTabOrder(self.pushButton_loadRadius, self.lineEdit_Gearbox)
        O2Tool.setTabOrder(self.lineEdit_Gearbox, self.pushButton_enableGearbox)
        O2Tool.setTabOrder(self.pushButton_enableGearbox, self.pushButton_disableGearbox)
        O2Tool.setTabOrder(self.pushButton_disableGearbox, self.pushButton_loadgearbox)
        O2Tool.setTabOrder(self.pushButton_loadgearbox, self.checkBox_turbineOP)
        O2Tool.setTabOrder(self.checkBox_turbineOP, self.pushButton_SClist)
        O2Tool.setTabOrder(self.pushButton_SClist, self.tabWidget)
        O2Tool.setTabOrder(self.tabWidget, self.pushButton_enablesimu)
        O2Tool.setTabOrder(self.pushButton_enablesimu, self.pushButton_ResetSaftyChain )
        O2Tool.setTabOrder(self.pushButton_ResetSaftyChain,self.pushButton_limitPower)
        O2Tool.setTabOrder(self.pushButton_limitPower, self.pushButton_bp50)
        O2Tool.setTabOrder(self.pushButton_bp50, self.pushButton_bp51)
        O2Tool.setTabOrder(self.pushButton_bp51, self.pushButton_bp100)
        O2Tool.setTabOrder(self.pushButton_bp100, self.pushButton_bp150)
        O2Tool.setTabOrder(self.pushButton_bp150, self.pushButton_bp199)
        O2Tool.setTabOrder(self.pushButton_bp199, self.pushButton_highwind)
        O2Tool.setTabOrder(self.pushButton_highwind, self.pushButton_highwindStop)
        O2Tool.setTabOrder(self.pushButton_highwindStop, self.pushButton_lowwind)
        O2Tool.setTabOrder(self.pushButton_lowwind, self.pushButton_lowwindStop)
        O2Tool.setTabOrder(self.pushButton_lowwindStop, self.lineEdit_SCcode)
        O2Tool.setTabOrder(self.lineEdit_SCcode, self.pushButton_loadSC)
        O2Tool.setTabOrder(self.pushButton_loadSC, self.lineEdit_SCsetType)
        O2Tool.setTabOrder(self.lineEdit_SCsetType, self.pushButton_setSCmode)
        O2Tool.setTabOrder(self.pushButton_setSCmode, self.lineEdit_SCsetdelay)
        O2Tool.setTabOrder(self.lineEdit_SCsetdelay, self.pushButton_setSCdelay)
        O2Tool.setTabOrder(self.pushButton_setSCdelay, self.lineEdit_SCresetDelay)
        O2Tool.setTabOrder(self.lineEdit_SCresetDelay, self.pushButton_setSCredelay)
        O2Tool.setTabOrder(self.pushButton_setSCredelay, self.lineEdit_SCrepeatTimes)
        O2Tool.setTabOrder(self.lineEdit_SCrepeatTimes, self.pushButton_setSCrepeat)
        O2Tool.setTabOrder(self.pushButton_setSCrepeat, self.pushButton_disableSC)
        O2Tool.setTabOrder(self.pushButton_disableSC, self.lineEdit_SCid)
        O2Tool.setTabOrder(self.lineEdit_SCid, self.lineEdit_ip_recorder)
        O2Tool.setTabOrder(self.lineEdit_ip_recorder, self.textEdit_var_recorder)
        O2Tool.setTabOrder(self.textEdit_var_recorder, self.lineEdit_ter_recorder)
        O2Tool.setTabOrder(self.lineEdit_ter_recorder, self.lineEdit_long_recorder)
        O2Tool.setTabOrder(self.lineEdit_long_recorder, self.pushButton_savevar)
        O2Tool.setTabOrder(self.pushButton_savevar, self.pushButton_startRecorder)
        O2Tool.setTabOrder(self.pushButton_startRecorder, self.pushButton_stopRecorder)
        O2Tool.setTabOrder(self.pushButton_stopRecorder, self.pushButton_openFileDir)
        O2Tool.setTabOrder(self.pushButton_openFileDir, self.lineEdit_SCbplevel)        
        O2Tool.setTabOrder(self.lineEdit_SCbplevel, self.pushButton_setSCbplevel)
        

    def retranslateUi(self, O2Tool):
        O2Tool.setWindowTitle(_translate("O2Tool", "O2Tool", None))
        self.groupBox_2.setTitle(_translate("O2Tool", "常用变量", None))
        self.pushButton_loadRadius.setText(_translate("O2Tool", "Load", None))
        self.label_10.setText(_translate("O2Tool", "Gearbox_limit:", None))
        self.pushButton_loadgearbox.setText(_translate("O2Tool", "Load", None))
        self.pushButton_setRadius.setText(_translate("O2Tool", "Set", None))
        self.label_9.setText(_translate("O2Tool", "Rotor Radius:", None))
        self.pushButton_enableGearbox.setText(_translate("O2Tool", "1", None))
        self.pushButton_disableGearbox.setText(_translate("O2Tool", "0", None))
        self.pushButton_loadWindspeed.setText(_translate("O2Tool", "Load", None))
        self.pushButton_resetScada.setText(_translate("O2Tool", "Reset", None))
        self.label_11.setText(_translate("O2Tool", "Wind_Speed:", None))
        self.pushButton_setWindspeed.setText(_translate("O2Tool", "Set", None))
        self.pushButton_loadScada.setText(_translate("O2Tool", "Load", None))
        self.label_8.setText(_translate("O2Tool", "Scada_limit:", None))
        self.pushButton_setScada.setText(_translate("O2Tool", "Set", None))        
        self.label_42.setText(_translate("O2Tool", "版本选择:", None))
        self.groupBox_3.setTitle(_translate("O2Tool", "ADS", None))
        self.label.setText(_translate("O2Tool", "Connect IP:", None))
        self.pushButton_adsConnect.setText(_translate("O2Tool", "Connect", None))
        self.label_4.setText(_translate("O2Tool", "Var Name:", None))
        self.pushButton_adsLoad.setText(_translate("O2Tool", "Load", None))
        self.label_3.setText(_translate("O2Tool", "Var Type:", None))
        self.label_5.setText(_translate("O2Tool", "Var Value:", None))
        self.pushButton_adsTrigger.setText(_translate("O2Tool", "Trigger", None))
        self.label_6.setText(_translate("O2Tool", "Set Value:", None))
        self.pushButton_adsWrite.setText(_translate("O2Tool", "Write", None))
        self.lineEdit_port.setText(_translate("O2Tool", "801", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ADS), _translate("O2Tool", "ADS", None))
        self.groupBox.setTitle(_translate("O2Tool", "SC 属性修改", None))
        self.label_25.setText(_translate("O2Tool", "ID:", None))
        self.label_yp.setText(_translate("O2Tool", "偏航等级", None))
        self.pushButton_disableSC.setText(_translate("O2Tool", "禁用SC", None))
        self.pushButton_disableSClist.setText(_translate("O2Tool", "禁用SC列表", None)) 
        self.pushButton_setSCrepeat.setText(_translate("O2Tool", "Set", None))
        self.label_19.setText(_translate("O2Tool", "SC编号：", None))
        self.label_20.setText(_translate("O2Tool", "复位方式：", None))
        self.pushButton_loadSC.setText(_translate("O2Tool", "Load", None))
        self.label_23.setText(_translate("O2Tool", "触发延时：", None))
        self.pushButton_setSCmode.setText(_translate("O2Tool", "Set", None))
        self.label_24.setText(_translate("O2Tool", "复位延时：", None))
        self.label_26.setText(_translate("O2Tool", "重复次数：", None))
        self.pushButton_setSCdelay.setText(_translate("O2Tool", "Set", None))
        self.pushButton_setSCredelay.setText(_translate("O2Tool", "Set", None))
        self.label_27.setText(_translate("O2Tool", "刹车等级：", None))
        self.pushButton_setSCbplevel.setText(_translate("O2Tool", "Set", None))
        self.pushButton_setSCyplevel.setText(_translate("O2Tool", "Set", None))
        self.pushButton_bp150.setText(_translate("O2Tool", "BP_150", None))
        self.pushButton_bp50.setText(_translate("O2Tool", "BP_50", None))
        self.pushButton_bp100.setText(_translate("O2Tool", "BP_100", None))
        self.pushButton_enablesimu.setText(_translate("O2Tool", "Enable_Simu", None))
        self.pushButton_bp199.setText(_translate("O2Tool", "BP_199", None))
        self.label_bp.setText(_translate("O2Tool", "刹车等级：", None))
        self.label_simu.setText(_translate("O2Tool", "仿真器：", None))
        self.pushButton_bp51.setText(_translate("O2Tool", "BP_51", None))
        self.label_test.setText(_translate("O2Tool", "测试辅助：", None))
        self.pushButton_limitPower.setText(_translate("O2Tool", "SCADA限功率", None))
        self.pushButton_highwind.setText(_translate("O2Tool", "大风起机", None))
        self.pushButton_highwindStop.setText(_translate("O2Tool", "大风停机", None))
        self.pushButton_lowwind.setText(_translate("O2Tool", "小风起机", None))
        self.pushButton_lowwindStop.setText(_translate("O2Tool", "小风停机", None))        
        self.pushButton_ResetSaftyChain.setText(_translate("O2Tool", "复位安全链", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("O2Tool", "常用功能", None))
        self.label_16.setText(_translate("O2Tool", "变量格式:\n"".grwindspeed\n"".giState\n", None))
        self.label_21.setText(_translate("O2Tool", "毫秒", None))
        self.label_22.setText(_translate("O2Tool", "秒", None))
        self.lineEdit_long_recorder.setText(_translate("O2Tool", "3000", None))
        self.label_17.setText(_translate("O2Tool", "录制间隔:", None))
        self.lineEdit_ter_recorder.setText(_translate("O2Tool", "10", None))
        self.label_18.setText(_translate("O2Tool", "录制长度:", None))
        self.label_14.setText(_translate("O2Tool", "Connect IP:   ", None))
        self.label_15.setText(_translate("O2Tool", "Var List:", None))
        self.pushButton_savevar.setText(_translate("O2Tool", "保存变量列表", None))
        self.pushButton_startRecorder.setText(_translate("O2Tool", "开始录制", None))
        self.pushButton_stopRecorder.setText(_translate("O2Tool", "停止", None))
        self.pushButton_openFileDir.setText(_translate("O2Tool", "打开数据目录", None))        
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("O2Tool", "DataRecorder", None))
        self.checkBox_turbineOP.setText(_translate("O2Tool", "风机状态刷新", None))
        self.pushButton_SClist.setText(_translate("O2Tool", "风机SC", None))
        self.label_power.setText(_translate("O2Tool", "功率：", None))
        self.label_genspeed.setText(_translate("O2Tool", "转速：", None))
        self.label_windspeed.setText(_translate("O2Tool", "风速：", None))
        self.label_turbineOP.setText(_translate("O2Tool", "风机状态：", None))
        self.label_bplevel.setText(_translate("O2Tool", "刹车等级：", None))
        self.label_yplevel.setText(_translate("O2Tool", "偏航等级：", None))
        self.pushButton_traclogDone.setText(_translate("O2Tool", "Tracelog", None))

        self.label_7.setText(_translate("O2Tool", "Var Name 1:", None))
        self.pushButton_batchRead1.setText(_translate("O2Tool", "Load", None))
        self.pushButton_batchWrite1.setText(_translate("O2Tool", "Write", None))
        self.label_28.setText(_translate("O2Tool", "Var Name 2:", None))
        self.pushButton_batchRead2.setText(_translate("O2Tool", "Load", None))
        self.pushButton_batchWrite2.setText(_translate("O2Tool", "Write", None))
        self.label_29.setText(_translate("O2Tool", "Var Name 3:", None))
        self.pushButton_batchRead3.setText(_translate("O2Tool", "Load", None))
        self.pushButton_batchWrite3.setText(_translate("O2Tool", "Write", None))
        self.label_30.setText(_translate("O2Tool", "Var Name 4:", None))
        self.pushButton_batchRead4.setText(_translate("O2Tool", "Load", None))
        self.pushButton_batchWrite4.setText(_translate("O2Tool", "Write", None))
        self.label_34.setText(_translate("O2Tool", "Var Name 5:", None))
        self.pushButton_batchRead8.setText(_translate("O2Tool", "Load", None))
        self.pushButton_batchWrite5.setText(_translate("O2Tool", "Write", None))
        self.label_31.setText(_translate("O2Tool", "Var Name 6:", None))
        self.pushButton_batchRead5.setText(_translate("O2Tool", "Load", None))
        self.pushButton_batchWrite6.setText(_translate("O2Tool", "Write", None))
        self.label_32.setText(_translate("O2Tool", "Var Name 7:", None))
        self.pushButton_batchRead7.setText(_translate("O2Tool", "Load", None))
        self.pushButton_batchWrite7.setText(_translate("O2Tool", "Write", None))
        self.label_33.setText(_translate("O2Tool", "Var Name 8:", None))
        self.pushButton_batchRead6.setText(_translate("O2Tool", "Load", None))
        self.pushButton_batchWrite8.setText(_translate("O2Tool", "Write", None))
        self.label_38.setText(_translate("O2Tool", "Var Name 9:", None))
        self.pushButton_batchRead9.setText(_translate("O2Tool", "Load", None))
        self.pushButton_batchWrite9.setText(_translate("O2Tool", "Write", None))
        self.label_35.setText(_translate("O2Tool", "Var Name 10:", None))
        self.pushButton_batchRead10.setText(_translate("O2Tool", "Load", None))
        self.pushButton_batchWrite10.setText(_translate("O2Tool", "Write", None))
        self.label_36.setText(_translate("O2Tool", "Var Name 11:", None))
        self.pushButton_batchRead11.setText(_translate("O2Tool", "Load", None))
        self.pushButton_batchWrite11.setText(_translate("O2Tool", "Write", None))
        self.label_37.setText(_translate("O2Tool", "Var Name 12:", None))
        self.pushButton_batchRead12.setText(_translate("O2Tool", "Load", None))
        self.pushButton_batchWrite12.setText(_translate("O2Tool", "Write", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_BatchRead), _translate("O2Tool", "批量读", None))
        self.label_39.setText(_translate("O2Tool", "Connect IP:   ", None))
        self.label_40.setText(_translate("O2Tool", "Var List:", None))
        self.pushButton_batchCheck.setText(_translate("O2Tool", "Check", None))
        self.pushButton_batchWrite.setText(_translate("O2Tool", "Write", None))
        self.pushButton_batchClean.setText(_translate("O2Tool", "Clean", None))        
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_BatchWrite), _translate("O2Tool", "批量写", None))
        self.label_41.setText(_translate("O2Tool", "Connect IP:   ", None))
        self.pushButton_batchReadAll.setText(_translate("O2Tool", "Load ALL", None))
        self.pushButton_batchWriteAll.setText(_translate("O2Tool", "Write ALL", None))
        self.pushButton_batchConnect.setText(_translate("O2Tool", "Connect", None))
        
if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    O2Tool = QMainWindow()
    ui = Ui_O2Tool()
    ui.setupUi(O2Tool)
    O2Tool.show()
    sys.exit(app.exec_())

